# Generated by Django 5.2.8 on 2025-11-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рубрика",
                "verbose_name_plural": "Рубрики",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="bb",
            options={
                "ordering": ["-published"],
                "verbose_name": "Объявления",
                "verbose_name_plural": " Объявления ",
            },
        ),
        migrations.AlterField(
            model_name="bb",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="bb",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="bb",
            name="published",
            field=models.DateField(
                auto_now_add=True, db_index=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="bb",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Product"),
        ),
        migrations.AddField(
            model_name="bb",
            name="rubric",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bboard.rubric",
                verbose_name="Рубрика",
            ),
        ),
    ]
